AWSTemplateFormatVersion: "2010-09-09"
Description: CI/CD Infrastructure using CloudFormation (with separate EC2 and CodeDeploy roles)

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 SSH Key

  VPCId:
    Type: String
    Description: "(Optional) VPC Id to attach security group to; leave blank to use default VPC"
    Default: ""

Resources:

  # ===============================
  # EC2 Security Group
  # ===============================
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Node.js
      VpcId: !If 
        - HasVPC
        - !Ref VPCId
        - !Ref "AWS::NoValue"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0

  # ===============================
  # Conditions
  # ===============================
  HasVPC:
    !Not [ !Equals [ !Ref VPCId, "" ] ]

  # ===============================
  # EC2 IAM Role
  # ===============================
  EC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2Role

  # ===============================
  # CodeDeploy IAM Role
  # ===============================
  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  # ===============================
  # S3 Bucket for deployment
  # ===============================
  DeploymentBucket:
    Type: AWS::S3::Bucket

  # ===============================
  # CodeDeploy Application
  # ===============================
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application

  # ===============================
  # CodeDeploy Deployment Group
  # ===============================
  CodeDeployGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      ServiceRoleArn: !GetAtt CodeDeployRole.Arn
      DeploymentConfigName: CodeDeployDefault.AllAtOnce

  # ===============================
  # EC2 Instance
  # ===============================
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      ImageId: ami-0c02fb55956c7d316
      IamInstanceProfile: !Ref EC2InstanceProfile
      SecurityGroupIds:
        - !Ref EC2SecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y ruby nodejs
          cd /home/ec2-user
          wget https://aws-codedeploy-us-e
